/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Formation } from "./Formation";
import { FormationCountArgs } from "./FormationCountArgs";
import { FormationFindManyArgs } from "./FormationFindManyArgs";
import { FormationFindUniqueArgs } from "./FormationFindUniqueArgs";
import { DeleteFormationArgs } from "./DeleteFormationArgs";
import { FormationService } from "../formation.service";
@graphql.Resolver(() => Formation)
export class FormationResolverBase {
  constructor(protected readonly service: FormationService) {}

  async _formationsMeta(
    @graphql.Args() args: FormationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Formation])
  async formations(
    @graphql.Args() args: FormationFindManyArgs
  ): Promise<Formation[]> {
    return this.service.formations(args);
  }

  @graphql.Query(() => Formation, { nullable: true })
  async formation(
    @graphql.Args() args: FormationFindUniqueArgs
  ): Promise<Formation | null> {
    const result = await this.service.formation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Formation)
  async deleteFormation(
    @graphql.Args() args: DeleteFormationArgs
  ): Promise<Formation | null> {
    try {
      return await this.service.deleteFormation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
