/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ParrainageService } from "../parrainage.service";
import { ParrainageCreateInput } from "./ParrainageCreateInput";
import { Parrainage } from "./Parrainage";
import { ParrainageFindManyArgs } from "./ParrainageFindManyArgs";
import { ParrainageWhereUniqueInput } from "./ParrainageWhereUniqueInput";
import { ParrainageUpdateInput } from "./ParrainageUpdateInput";

export class ParrainageControllerBase {
  constructor(protected readonly service: ParrainageService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Parrainage })
  async createParrainage(
    @common.Body() data: ParrainageCreateInput
  ): Promise<Parrainage> {
    return await this.service.createParrainage({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Parrainage] })
  @ApiNestedQuery(ParrainageFindManyArgs)
  async parrainages(@common.Req() request: Request): Promise<Parrainage[]> {
    const args = plainToClass(ParrainageFindManyArgs, request.query);
    return this.service.parrainages({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Parrainage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async parrainage(
    @common.Param() params: ParrainageWhereUniqueInput
  ): Promise<Parrainage | null> {
    const result = await this.service.parrainage({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Parrainage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateParrainage(
    @common.Param() params: ParrainageWhereUniqueInput,
    @common.Body() data: ParrainageUpdateInput
  ): Promise<Parrainage | null> {
    try {
      return await this.service.updateParrainage({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Parrainage })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteParrainage(
    @common.Param() params: ParrainageWhereUniqueInput
  ): Promise<Parrainage | null> {
    try {
      return await this.service.deleteParrainage({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
