/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Parrainage as PrismaParrainage } from "@prisma/client";

export class ParrainageServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ParrainageCountArgs, "select">
  ): Promise<number> {
    return this.prisma.parrainage.count(args);
  }

  async parrainages(
    args: Prisma.ParrainageFindManyArgs
  ): Promise<PrismaParrainage[]> {
    return this.prisma.parrainage.findMany(args);
  }
  async parrainage(
    args: Prisma.ParrainageFindUniqueArgs
  ): Promise<PrismaParrainage | null> {
    return this.prisma.parrainage.findUnique(args);
  }
  async createParrainage(
    args: Prisma.ParrainageCreateArgs
  ): Promise<PrismaParrainage> {
    return this.prisma.parrainage.create(args);
  }
  async updateParrainage(
    args: Prisma.ParrainageUpdateArgs
  ): Promise<PrismaParrainage> {
    return this.prisma.parrainage.update(args);
  }
  async deleteParrainage(
    args: Prisma.ParrainageDeleteArgs
  ): Promise<PrismaParrainage> {
    return this.prisma.parrainage.delete(args);
  }
}
