/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Parrainage } from "./Parrainage";
import { ParrainageCountArgs } from "./ParrainageCountArgs";
import { ParrainageFindManyArgs } from "./ParrainageFindManyArgs";
import { ParrainageFindUniqueArgs } from "./ParrainageFindUniqueArgs";
import { DeleteParrainageArgs } from "./DeleteParrainageArgs";
import { ParrainageService } from "../parrainage.service";
@graphql.Resolver(() => Parrainage)
export class ParrainageResolverBase {
  constructor(protected readonly service: ParrainageService) {}

  async _parrainagesMeta(
    @graphql.Args() args: ParrainageCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Parrainage])
  async parrainages(
    @graphql.Args() args: ParrainageFindManyArgs
  ): Promise<Parrainage[]> {
    return this.service.parrainages(args);
  }

  @graphql.Query(() => Parrainage, { nullable: true })
  async parrainage(
    @graphql.Args() args: ParrainageFindUniqueArgs
  ): Promise<Parrainage | null> {
    const result = await this.service.parrainage(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Parrainage)
  async deleteParrainage(
    @graphql.Args() args: DeleteParrainageArgs
  ): Promise<Parrainage | null> {
    try {
      return await this.service.deleteParrainage(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
