/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Recrue } from "./Recrue";
import { RecrueCountArgs } from "./RecrueCountArgs";
import { RecrueFindManyArgs } from "./RecrueFindManyArgs";
import { RecrueFindUniqueArgs } from "./RecrueFindUniqueArgs";
import { CreateRecrueArgs } from "./CreateRecrueArgs";
import { UpdateRecrueArgs } from "./UpdateRecrueArgs";
import { DeleteRecrueArgs } from "./DeleteRecrueArgs";
import { RecrueService } from "../recrue.service";
@graphql.Resolver(() => Recrue)
export class RecrueResolverBase {
  constructor(protected readonly service: RecrueService) {}

  async _recruesMeta(
    @graphql.Args() args: RecrueCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Recrue])
  async recrues(@graphql.Args() args: RecrueFindManyArgs): Promise<Recrue[]> {
    return this.service.recrues(args);
  }

  @graphql.Query(() => Recrue, { nullable: true })
  async recrue(
    @graphql.Args() args: RecrueFindUniqueArgs
  ): Promise<Recrue | null> {
    const result = await this.service.recrue(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Recrue)
  async createRecrue(@graphql.Args() args: CreateRecrueArgs): Promise<Recrue> {
    return await this.service.createRecrue({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Recrue)
  async updateRecrue(
    @graphql.Args() args: UpdateRecrueArgs
  ): Promise<Recrue | null> {
    try {
      return await this.service.updateRecrue({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Recrue)
  async deleteRecrue(
    @graphql.Args() args: DeleteRecrueArgs
  ): Promise<Recrue | null> {
    try {
      return await this.service.deleteRecrue(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
