/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Recrue as PrismaRecrue } from "@prisma/client";

export class RecrueServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.RecrueCountArgs, "select">): Promise<number> {
    return this.prisma.recrue.count(args);
  }

  async recrues(args: Prisma.RecrueFindManyArgs): Promise<PrismaRecrue[]> {
    return this.prisma.recrue.findMany(args);
  }
  async recrue(
    args: Prisma.RecrueFindUniqueArgs
  ): Promise<PrismaRecrue | null> {
    return this.prisma.recrue.findUnique(args);
  }
  async createRecrue(args: Prisma.RecrueCreateArgs): Promise<PrismaRecrue> {
    return this.prisma.recrue.create(args);
  }
  async updateRecrue(args: Prisma.RecrueUpdateArgs): Promise<PrismaRecrue> {
    return this.prisma.recrue.update(args);
  }
  async deleteRecrue(args: Prisma.RecrueDeleteArgs): Promise<PrismaRecrue> {
    return this.prisma.recrue.delete(args);
  }
}
