/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RecrueService } from "../recrue.service";
import { RecrueCreateInput } from "./RecrueCreateInput";
import { Recrue } from "./Recrue";
import { RecrueFindManyArgs } from "./RecrueFindManyArgs";
import { RecrueWhereUniqueInput } from "./RecrueWhereUniqueInput";
import { RecrueUpdateInput } from "./RecrueUpdateInput";

export class RecrueControllerBase {
  constructor(protected readonly service: RecrueService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Recrue })
  async createRecrue(@common.Body() data: RecrueCreateInput): Promise<Recrue> {
    return await this.service.createRecrue({
      data: data,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Recrue] })
  @ApiNestedQuery(RecrueFindManyArgs)
  async recrues(@common.Req() request: Request): Promise<Recrue[]> {
    const args = plainToClass(RecrueFindManyArgs, request.query);
    return this.service.recrues({
      ...args,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Recrue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async recrue(
    @common.Param() params: RecrueWhereUniqueInput
  ): Promise<Recrue | null> {
    const result = await this.service.recrue({
      where: params,
      select: {
        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Recrue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRecrue(
    @common.Param() params: RecrueWhereUniqueInput,
    @common.Body() data: RecrueUpdateInput
  ): Promise<Recrue | null> {
    try {
      return await this.service.updateRecrue({
        where: params,
        data: data,
        select: {
          createdAt: true,
          firstName: true,
          id: true,
          lastName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Recrue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRecrue(
    @common.Param() params: RecrueWhereUniqueInput
  ): Promise<Recrue | null> {
    try {
      return await this.service.deleteRecrue({
        where: params,
        select: {
          createdAt: true,
          firstName: true,
          id: true,
          lastName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
