/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ContactParraine as PrismaContactParraine,
} from "@prisma/client";

export class ContactParraineServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ContactParraineCountArgs, "select">
  ): Promise<number> {
    return this.prisma.contactParraine.count(args);
  }

  async contactParraines(
    args: Prisma.ContactParraineFindManyArgs
  ): Promise<PrismaContactParraine[]> {
    return this.prisma.contactParraine.findMany(args);
  }
  async contactParraine(
    args: Prisma.ContactParraineFindUniqueArgs
  ): Promise<PrismaContactParraine | null> {
    return this.prisma.contactParraine.findUnique(args);
  }
  async createContactParraine(
    args: Prisma.ContactParraineCreateArgs
  ): Promise<PrismaContactParraine> {
    return this.prisma.contactParraine.create(args);
  }
  async updateContactParraine(
    args: Prisma.ContactParraineUpdateArgs
  ): Promise<PrismaContactParraine> {
    return this.prisma.contactParraine.update(args);
  }
  async deleteContactParraine(
    args: Prisma.ContactParraineDeleteArgs
  ): Promise<PrismaContactParraine> {
    return this.prisma.contactParraine.delete(args);
  }
}
