/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ContactParraineService } from "../contactParraine.service";
import { ContactParraineCreateInput } from "./ContactParraineCreateInput";
import { ContactParraine } from "./ContactParraine";
import { ContactParraineFindManyArgs } from "./ContactParraineFindManyArgs";
import { ContactParraineWhereUniqueInput } from "./ContactParraineWhereUniqueInput";
import { ContactParraineUpdateInput } from "./ContactParraineUpdateInput";

export class ContactParraineControllerBase {
  constructor(protected readonly service: ContactParraineService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ContactParraine })
  async createContactParraine(
    @common.Body() data: ContactParraineCreateInput
  ): Promise<ContactParraine> {
    return await this.service.createContactParraine({
      data: data,
      select: {
        createdAt: true,
        firstname: true,
        id: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [ContactParraine] })
  @ApiNestedQuery(ContactParraineFindManyArgs)
  async contactParraines(
    @common.Req() request: Request
  ): Promise<ContactParraine[]> {
    const args = plainToClass(ContactParraineFindManyArgs, request.query);
    return this.service.contactParraines({
      ...args,
      select: {
        createdAt: true,
        firstname: true,
        id: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ContactParraine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async contactParraine(
    @common.Param() params: ContactParraineWhereUniqueInput
  ): Promise<ContactParraine | null> {
    const result = await this.service.contactParraine({
      where: params,
      select: {
        createdAt: true,
        firstname: true,
        id: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ContactParraine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateContactParraine(
    @common.Param() params: ContactParraineWhereUniqueInput,
    @common.Body() data: ContactParraineUpdateInput
  ): Promise<ContactParraine | null> {
    try {
      return await this.service.updateContactParraine({
        where: params,
        data: data,
        select: {
          createdAt: true,
          firstname: true,
          id: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ContactParraine })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteContactParraine(
    @common.Param() params: ContactParraineWhereUniqueInput
  ): Promise<ContactParraine | null> {
    try {
      return await this.service.deleteContactParraine({
        where: params,
        select: {
          createdAt: true,
          firstname: true,
          id: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
