/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ContactParraine } from "./ContactParraine";
import { ContactParraineCountArgs } from "./ContactParraineCountArgs";
import { ContactParraineFindManyArgs } from "./ContactParraineFindManyArgs";
import { ContactParraineFindUniqueArgs } from "./ContactParraineFindUniqueArgs";
import { CreateContactParraineArgs } from "./CreateContactParraineArgs";
import { UpdateContactParraineArgs } from "./UpdateContactParraineArgs";
import { DeleteContactParraineArgs } from "./DeleteContactParraineArgs";
import { ContactParraineService } from "../contactParraine.service";
@graphql.Resolver(() => ContactParraine)
export class ContactParraineResolverBase {
  constructor(protected readonly service: ContactParraineService) {}

  async _contactParrainesMeta(
    @graphql.Args() args: ContactParraineCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ContactParraine])
  async contactParraines(
    @graphql.Args() args: ContactParraineFindManyArgs
  ): Promise<ContactParraine[]> {
    return this.service.contactParraines(args);
  }

  @graphql.Query(() => ContactParraine, { nullable: true })
  async contactParraine(
    @graphql.Args() args: ContactParraineFindUniqueArgs
  ): Promise<ContactParraine | null> {
    const result = await this.service.contactParraine(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ContactParraine)
  async createContactParraine(
    @graphql.Args() args: CreateContactParraineArgs
  ): Promise<ContactParraine> {
    return await this.service.createContactParraine({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ContactParraine)
  async updateContactParraine(
    @graphql.Args() args: UpdateContactParraineArgs
  ): Promise<ContactParraine | null> {
    try {
      return await this.service.updateContactParraine({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ContactParraine)
  async deleteContactParraine(
    @graphql.Args() args: DeleteContactParraineArgs
  ): Promise<ContactParraine | null> {
    try {
      return await this.service.deleteContactParraine(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
